name: CI • Build • Test • Scan

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'infra/terraform/**'
      - '.github/workflows/ci-app.yml'
  workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Maven + Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & test
        working-directory: backend
        run: mvn -B -U clean verify

      - name: Enable Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build (local only)
        run: docker build -t local/backend:${{ github.sha }} -f backend/Dockerfile backend

      - name: Trivy FS scan (source)
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          scan-type: fs
          scan-ref: backend
          format: table
          exit-code: "1"
          ignore-unfixed: true

      - name: Trivy Image scan (local image)
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          image-ref: local/backend:${{ github.sha }}
          format: table
          exit-code: "1"
          ignore-unfixed: true

  frontend:
    name: Frontend (Node/Vite + Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Lint
        working-directory: frontend
        run: npm run lint --if-present

      - name: Test
        working-directory: frontend
        run: npm test --if-present -- --run

      - name: Build (Vite)
        working-directory: frontend
        run: npm run build

      - name: Enable Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build (local only)
        run: docker build -t local/frontend:${{ github.sha }} -f frontend/Dockerfile frontend

      - name: Trivy FS scan (source)
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          scan-type: fs
          scan-ref: frontend
          format: table
          exit-code: "1"
          ignore-unfixed: true

      - name: Trivy Image scan (local image)
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          image-ref: local/frontend:${{ github.sha }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
