name: CI • Build • Test

on:
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci-app.yml"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: backend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & Test
        run: mvn -B -U clean verify
      # optional: ensure Dockerfile builds
      - name: Docker build (optional)
        run: docker build -t local/backend:${{ github.sha }} -f backend/Dockerfile backend

  frontend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: frontend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present -- --run
      - run: npm run build
      # optional: ensure Dockerfile builds
      - name: Docker build (optional)
        run: docker build -t local/frontend:${{ github.sha }} -f frontend/Dockerfile frontend
